username: ken
default-branch: main
repository-commands:
  - quest:
    - Write-Host 'Copying .vs folder' ; Copy-Item "$((Get-Worktrees)['main'])\.vs" . -Recurse -Force
    - cd ui
    - npm install
    - cd ..
